display: ":0"
xauthority: "~/.Xauthority"

ska-tango-base:
  deviceServers: []

enabled: true

system: SW-infrastructure
subsystem: ska-csp-lmc
telescope: SKA

labels:
  app: ska-csp-simulators

vaultAddress: "https://vault.skao.int"

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"
  DEBUG: 5678

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

dsconfig:
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.4.3
    pullPolicy: IfNotPresent

simul:
  image:
    registry: harbor.skao.int/staging
    image: ska-csp-simulators
    tag: 0.3.1
    pullPolicy: IfNotPresent

volume:
  image:
    registry: "docker.io"
    image: "alpine"
    tag: "3.12"
    pullPolicy: "IfNotPresent"

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

# Splitted deviceServers into a servers variable
# to be able to disable all device servers or a particular
# device server without deleting things or by using a values
# file by doing:
# > K8S_EXTRA_PARAMS="--values $(pwd)/values.yaml" make k8s-install-chart

deviceServers:
  enabled: true
  servers:
    midcbfctrl:
      enabled: true
      file: "data/beginner/midcbfctrl.yaml"
    midcbfsubarray:
      enabled: true
      file: "data/beginner/midcbfsubarray.yaml"
    midpssctrl:
      enabled: true
      file: "data/beginner/midpssctrl.yaml"
    midpsssubarray:
      enabled: true
      file: "data/beginner/midpsssubarray.yaml"
    midpstbeam:
      enabled: true
      file: "data/beginner/midpstbeam.yaml"
    lowcbfctrl:
      enabled: true
      file: "data/beginner/lowcbfctrl.yaml"
    lowcbfsubarray:
      enabled: true
      file: "data/beginner/lowcbfsubarray.yaml"
    lowpssctrl:
      enabled: true
      file: "data/beginner/lowpssctrl.yaml"
    lowpsssubarray:
      enabled: true
      file: "data/beginner/lowpsssubarray.yaml"
    lowpstbeam:
      enabled: true
      file: "data/beginner/lowpstbeam.yaml"

nodeSelector: {}

affinity: {}

tolerations: []
